import test from 'node:test';
import assert from 'node:assert/strict';
import Database from './support/database.mjs';
import {initializeParticipantStore,recordParticipant,listParticipants} from '../src/lib/participantStore.mjs';
import {setParticipantBlacklist,isPhoneBlacklisted} from '../src/lib/participantBlacklist.mjs';
import {initializeRecallStore,saveRecallForm,bookRecall} from '../src/lib/recallStore.mjs';
import {initializeProjectMembers,importProjectMembers} from '../src/lib/projectMembers.mjs';
import {editParticipant} from '../src/lib/participantEditing.mjs';
async function setup(){const db=new Database();await db.exec("CREATE TABLE projects(id TEXT,name TEXT);CREATE TABLE surveys(id TEXT,title TEXT);CREATE TABLE responses(id TEXT,project_id TEXT,survey_id TEXT,respondent_phone TEXT,created_at TEXT);INSERT INTO projects VALUES('p','Dự án');");await initializeParticipantStore(db);await initializeRecallStore(db);await initializeProjectMembers(db);await recordParticipant(db,{id:'r',project_id:'p',respondent_name:'An',respondent_phone:'0901234567'});return db;}
test('blacklist persists, normalizes phone aliases, prevents silent phone changes and supports unblock',async()=>{const db=await setup();try{const id='phone:0901234567';assert.equal((await setParticipantBlacklist(db,id,true,'admin')).status,200);for(const phone of ['0901234567','+84 901 234 567','0084901234567'])assert.equal(await isPhoneBlacklisted(db,phone),true);await initializeParticipantStore(db);assert.equal((await listParticipants(db)).participants[0].blacklisted,true);assert.equal((await editParticipant(db,id,{respondent_phone:'0901234568'})).status,409);await recordParticipant(db,{id:'new',respondent_name:'An',respondent_phone:'0901234567'});assert.equal(await isPhoneBlacklisted(db,'0901234567'),true);await setParticipantBlacklist(db,id,false,'admin');assert.equal(await isPhoneBlacklisted(db,'0901234567'),false);assert.equal((await listParticipants(db)).participants[0].blacklisted,false);assert.equal((await setParticipantBlacklist(db,'missing',true,'admin')).status,404);assert.equal((await setParticipantBlacklist(db,id,'true','admin')).status,400);}finally{await db.close();}});
test('blocks Recall and Excel project registration and permits both again after unblock',async()=>{const db=await setup();try{const form=await saveRecallForm(db,{project_id:'p',title:'Recall',slots:['2030-10-01T09:00'],is_open:true,allow_overlap:true},{id:'admin',role:'admin'});const row={row:2,name:'An',phone:'0901234567',occupation:'NV',inviter:'Khánh'};await setParticipantBlacklist(db,'phone:0901234567',true,'admin');await assert.rejects(()=>bookRecall(db,form.share_token,{name:'An',phone:'+84901234567',starts_at:'2030-10-01T09:00'},new Date('2030-09-01')),e=>e.status===403);const result=await importProjectMembers(db,'p',[row],{commit:true,userId:'admin'});assert.equal(result.errors,1);assert.equal(result.added,0);assert.equal((await db.prepare('SELECT COUNT(*) AS n FROM recall_bookings').get()).n,0);await setParticipantBlacklist(db,'phone:0901234567',false,'admin');await bookRecall(db,form.share_token,{name:'An',phone:'0901234567',starts_at:'2030-10-01T09:00'},new Date('2030-09-01'));assert.equal((await importProjectMembers(db,'p',[row],{commit:true,userId:'admin'})).added,1);}finally{await db.close();}});
