import test from 'node:test';
import assert from 'node:assert/strict';
import Database from './support/database.mjs';
import {initializeSummaryStore,summaryConfig,saveSummaryTemplate,getParticipantSummary,renderParticipantSummary} from '../src/lib/participantSummary.mjs';
async function fixture(){const db=new Database();await db.exec(`CREATE TABLE projects(id TEXT PRIMARY KEY,name TEXT);CREATE TABLE surveys(id TEXT,project_id TEXT,title TEXT,fields_json TEXT);CREATE TABLE responses(id TEXT,project_id TEXT,survey_id TEXT,question_labels_json TEXT,data_json TEXT,respondent_name TEXT,respondent_bumo TEXT);CREATE TABLE project_members(project_id TEXT,participant_id TEXT);CREATE TABLE participants(id TEXT,profile_json TEXT);INSERT INTO projects VALUES('p','Dự án A'),('q','Dự án B');`);await initializeSummaryStore(db);await initializeSummaryStore(db);await db.prepare('INSERT INTO surveys VALUES(?,?,?,?)').run('s','p','Khảo sát A',JSON.stringify([{id:'section',type:'section',label:'Phần'},{id:'freq',type:'dropdown',label:'Tần suất'},{id:'brand',type:'checkbox',label:'Nhãn hiệu'}]));await db.prepare('INSERT INTO responses VALUES(?,?,?,?,?,?,?)').run('r','p','s','{}',JSON.stringify({freq:'Hàng ngày',brand:['A','B']}),'Nguyễn An','["A"]');return db;}
test('project templates render profile, BUMO and exact survey answer with missing fields explicit',async()=>{
 const db=await fixture();try{const config=await summaryConfig(db,'p');assert.ok(!config.sources.some(s=>s.id==='["s","section"]'));const template={intro:'Thông tin',outro:'Cảm ơn',rows:[{label:'Họ tên',source:'respondent_name'},{label:'BUMO',source:'respondent_bumo'},{label:'Tần suất',source:'["s","freq"]'},{label:'Các nhãn',source:'["s","brand"]'},{label:'Địa chỉ',source:'respondent_address'}]};await saveSummaryTemplate(db,'p',template);const result=await getParticipantSummary(db,'p',{responseId:'r'});assert.equal(result.text,'Thông tin\nHọ tên: Nguyễn An\nBUMO: A\nTần suất: Hàng ngày\nCác nhãn: A, B\nĐịa chỉ: Chưa có thông tin\nCảm ơn');assert.notDeepEqual((await summaryConfig(db,'q')).template,template);await assert.rejects(()=>getParticipantSummary(db,'q',{responseId:'r'}),e=>e.status===404);
 }finally{await db.close();}
});
test('templates reject foreign sources and invalid lengths; stored labels survive survey deletion',async()=>{
 const db=await fixture();try{await assert.rejects(()=>saveSummaryTemplate(db,'q',{intro:'',outro:'',rows:[{label:'Sai',source:'["s","freq"]'}]}));await assert.rejects(()=>saveSummaryTemplate(db,'p',{intro:'',outro:'',rows:[]}));await assert.rejects(()=>saveSummaryTemplate(db,'p',{intro:'x'.repeat(2001),outro:'',rows:[{label:'Tên',source:'respondent_name'}]}));await db.prepare('UPDATE responses SET question_labels_json = ?').run('{"freq":"Tần suất đã lưu"}');await db.exec('DELETE FROM surveys');assert.ok((await summaryConfig(db,'p')).sources.some(s=>s.id==='["s","freq"]'));await saveSummaryTemplate(db,'p',{intro:'',outro:'',rows:[{label:'Tần suất',source:'["s","freq"]'}]});assert.equal((await getParticipantSummary(db,'p',{responseId:'r'})).text,'Tần suất: Hàng ngày');
 }finally{await db.close();}
});
test('Excel members use current profile only within their project and do not invent survey answers',async()=>{
 const db=await fixture();try{await db.prepare('INSERT INTO participants VALUES(?,?)').run('person',JSON.stringify({respondent_name:'Người Excel',respondent_birth_year:1990}));await db.exec("INSERT INTO project_members VALUES('p','person')");await saveSummaryTemplate(db,'p',{intro:'',outro:'',rows:[{label:'Tên',source:'respondent_name'},{label:'Tần suất',source:'["s","freq"]'}]});assert.equal((await getParticipantSummary(db,'p',{participantId:'person'})).text,'Tên: Người Excel\nTần suất: Chưa có thông tin');await assert.rejects(()=>getParticipantSummary(db,'q',{participantId:'person'}),e=>e.status===404);
 }finally{await db.close();}
});
test('structured answers format readably and matching question ids in other surveys do not leak',()=>{
 const t={intro:'',outro:'',rows:[{label:'Ma trận',source:'["s","matrix"]'},{label:'Tệp',source:'["s","file"]'}]};const person={survey_id:'s',data_json:JSON.stringify({matrix:{A:['X','Y'],B:0},file:{kind:'file',name:'anh.png',data:'private-base64'}})};assert.equal(renderParticipantSummary(t,person,{}),'Ma trận: A: X, Y; B: 0\nTệp: anh.png');assert.ok(!renderParticipantSummary(t,{...person,survey_id:'other'},{}).includes('anh.png'));
});
