import test from 'node:test';
import assert from 'node:assert/strict';
import Database from './support/database.mjs';
import {copyProject} from '../src/lib/projectCopy.mjs';
async function fixture(){const db=new Database();await db.exec(`CREATE TABLE projects(id TEXT PRIMARY KEY,name TEXT,description TEXT,start_date TEXT,end_date TEXT,max_responses INTEGER,status TEXT,created_by TEXT,rules_json TEXT,summary_template_json TEXT);CREATE TABLE surveys(id TEXT PRIMARY KEY,project_id TEXT,title TEXT,description TEXT,fields_json TEXT,share_token TEXT UNIQUE,is_published INTEGER,created_at TEXT DEFAULT CURRENT_TIMESTAMP);CREATE TABLE responses(id TEXT,project_id TEXT);INSERT INTO responses VALUES('r','p');`);await db.prepare('INSERT INTO projects VALUES(?,?,?,?,?,?,?,?,?,?)').run('p','Gốc','Mô tả','2026-09-01','2026-09-30',100,'active','old','{"gender":{"enabled":true}}',JSON.stringify({intro:'Thông tin',outro:'',rows:[{label:'Tên',source:'respondent_name'},{label:'Tần suất',source:'["s","freq"]'},{label:'Cũ',source:'["deleted","q"]'}]}));await db.prepare('INSERT INTO surveys (id,project_id,title,description,fields_json,share_token,is_published) VALUES(?,?,?,?,?,?,?)').run('s','p','Khảo sát','Hướng dẫn',JSON.stringify([{id:'section',type:'section',next:'end'},{id:'freq',type:'dropdown',purpose:'bumo',options:['A'],logic:[{value:'A',target:'section'}]}]),'original-token',1);return db;}
test('copies settings/questions with new links, resets publication, remaps summaries and leaves source responses untouched',async()=>{
 const db=await fixture();try{const result=await copyProject(db,'p',{name:'Mới',start_date:'2026-10-01',end_date:'2026-10-31'},'admin');const project=await db.prepare('SELECT * FROM projects WHERE id=?').get(result.id);const survey=await db.prepare('SELECT * FROM surveys WHERE project_id=?').get(result.id);const original=await db.prepare('SELECT * FROM surveys WHERE id=?').get('s');assert.equal(result.survey_count,1);assert.equal(result.omitted_summary_fields,1);assert.equal(project.status,'inactive');assert.equal(project.created_by,'admin');assert.equal(project.start_date,'2026-10-01');assert.equal(project.max_responses,100);assert.equal(project.rules_json,'{"gender":{"enabled":true}}');assert.equal(survey.fields_json,original.fields_json);assert.notEqual(survey.share_token,original.share_token);assert.notEqual(survey.id,original.id);assert.equal(survey.is_published,0);assert.equal(JSON.parse(project.summary_template_json).rows[1].source,JSON.stringify([survey.id,'freq']));assert.equal((await db.prepare('SELECT COUNT(*) AS n FROM responses WHERE project_id=?').get(result.id)).n,0);assert.equal((await db.prepare('SELECT is_published FROM surveys WHERE id=?').get('s')).is_published,1);
 }finally{await db.close();}
});
test('validates names/dates, missing source and atomically rolls back failed copies',async()=>{
 const db=await fixture();try{await assert.rejects(()=>copyProject(db,'p',{name:'  '},'admin'));await assert.rejects(()=>copyProject(db,'p',{name:'Mới',start_date:'2026-02-30'},'admin'));await assert.rejects(()=>copyProject(db,'p',{name:'Mới',start_date:'2027-01-01',end_date:'2026-01-01'},'admin'));await assert.rejects(()=>copyProject(db,'missing',{name:'Mới'},'admin'),e=>e.status===404);await db.exec("CREATE TRIGGER fail_copy BEFORE INSERT ON surveys WHEN NEW.project_id != 'p' BEGIN SELECT RAISE(ABORT,'test failure'); END;");await assert.rejects(()=>copyProject(db,'p',{name:'Fail'},'admin'));assert.equal((await db.prepare('SELECT COUNT(*) AS n FROM projects').get()).n,1);
 }finally{await db.close();}
});
test('supports empty projects and repeat copies have separate IDs',async()=>{
 const db=await fixture();try{await db.exec('DELETE FROM surveys;UPDATE projects SET summary_template_json=NULL');const a=await copyProject(db,'p',{name:'A',start_date:'',end_date:''},'admin'),b=await copyProject(db,'p',{name:'B'},'admin');assert.equal(a.survey_count,0);assert.notEqual(a.id,b.id);}finally{await db.close();}
});
