'use client';
import {useState} from 'react';
import {useSession} from 'next-auth/react';
import {useRouter} from 'next/navigation';
import {useToast} from './Toast';
import Icon from './Icon';
import Modal from './Modal';
export default function CopyProject({project}){
 const {data:session}=useSession(),router=useRouter(),{addToast}=useToast();const [open,setOpen]=useState(false),[name,setName]=useState(''),[start,setStart]=useState(''),[end,setEnd]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 if(session?.user?.role!=='admin')return null;
 function show(){setName(`${project.name} (Bản sao)`.slice(0,200));setStart(project.start_date?.slice(0,10)||'');setEnd(project.end_date?.slice(0,10)||'');setError('');setOpen(true);}
 async function copy(e){e.preventDefault();if(busy)return;setBusy(true);setError('');try{const res=await fetch(`/api/projects/${encodeURIComponent(project.id)}/copy`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,start_date:start,end_date:end})});const data=await res.json();if(!res.ok)throw Error(data.error);addToast(`Đã sao chép dự án và ${data.survey_count} khảo sát`,'success');if(data.omitted_summary_fields)addToast(`Đã bỏ ${data.omitted_summary_fields} mục tóm tắt thuộc khảo sát không còn tồn tại.`,'info');setOpen(false);router.push(`/admin/projects/${data.id}`);}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <><button className="btn btn-secondary btn-icon" title="Sao chép dự án" aria-label={`Sao chép dự án ${project.name}`} onClick={e=>{e.stopPropagation();show();}}><Icon name="copy"/></button>{open&&<Modal isOpen onClose={()=>{if(!busy)setOpen(false);}} title="Sao chép dự án"><form onSubmit={copy} onClick={e=>e.stopPropagation()}><p className="form-hint">Sao chép mô tả, chỉ tiêu giới tính/tuổi/BUMO, mẫu tóm tắt và toàn bộ câu hỏi, chia phần, logic của các khảo sát. Mỗi khảo sát có link mới.</p><p className="form-hint">Dự án mới ở trạng thái Đóng, khảo sát là bản nháp để bạn kiểm tra trước khi mở Onfield. Không sao chép phản hồi, người tham gia, Form Recall, lịch hẹn hoặc giao mẫu.</p><fieldset className="recall-fieldset" disabled={busy}><label className="form-label">Tên dự án mới<input aria-label="Tên dự án mới" className="form-input" required maxLength={200} value={name} onChange={e=>setName(e.target.value)}/></label><div className="editor-grid" style={{marginTop:16}}><label className="form-label">Ngày bắt đầu<input aria-label="Ngày bắt đầu dự án mới" className="form-input" type="date" value={start} onChange={e=>setStart(e.target.value)}/></label><label className="form-label">Ngày kết thúc<input aria-label="Ngày kết thúc dự án mới" className="form-input" type="date" min={start||undefined} value={end} onChange={e=>setEnd(e.target.value)}/></label></div></fieldset>{error&&<p role="alert" className="recall-error">{error}</p>}<div className="recall-actions"><button type="button" className="btn btn-secondary" disabled={busy} onClick={()=>setOpen(false)}>Hủy</button><button className="btn btn-primary" disabled={busy}>{busy?'Đang sao chép…':'Tạo bản sao'}</button></div></form></Modal>}</>;
}
