'use client';
import {useState} from 'react';
import Modal from './Modal';
export default function ImportParticipants({onClose,onSaved,projectId,projectName}){
 const [file,setFile]=useState(null),[result,setResult]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[done,setDone]=useState(false);
 async function upload(commit=false){setBusy(true);setError('');try{const body=new FormData();body.set('file',file);body.set('commit',String(commit));const response=await fetch(projectId?`/api/projects/${encodeURIComponent(projectId)}/members/import`:'/api/participants/import',{method:'POST',body});const data=await response.json();if(!response.ok)throw Error(data.error||'Không thể nhập file.');setResult(data);if(commit){setDone(true);onSaved(data);}}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <Modal isOpen onClose={()=>{if(!busy)onClose();}} title={projectId?"Nhập người tham gia vào dự án":"Nhập data từ Excel"} size="lg">
  <p className="form-hint">Trang đầu tiên có hàng tiêu đề: Tên, Năm sinh, Số điện thoại, Địa chỉ, Nghề nghiệp, Tình trạng hôn nhân, Dự án tham gia, Người mời. Tên, Số điện thoại, Nghề nghiệp và Người mời là các mục bắt buộc; các mục còn lại có thể để trống hoặc không có cột. Người mời: Khánh hoặc Tế.</p>
  <p className="form-hint">Năm sinh: từ 1900 đến năm hiện tại. Tình trạng hôn nhân: Độc thân, Đã kết hôn - chưa con, Đã kết hôn - có con.</p>
  {projectId&&<p className="form-hint">Dự án: <strong>{projectName}</strong>. Người nhập thành công được duyệt ngay và xuất hiện trong Giao mẫu. Cột Dự án tham gia có thể để trống; tất cả được thêm vào dự án này.</p>}
  <p className="form-hint">Đặt cột số điện thoại thành Văn bản để giữ số 0 đầu. Mỗi dòng một hồ sơ, tối đa 1.000 dòng / 2 MB. {projectId?'Số điện thoại đã có trong Quản lý data sẽ dùng hồ sơ hiện có; số đã có trong dự án được bỏ qua.':'Số điện thoại trùng sẽ được bỏ qua, không ghi đè hồ sơ.'}</p>
  {projectId?<p className="form-hint">Đây là danh sách được quản trị viên duyệt trực tiếp, không qua sàng lọc tuổi/BUMO hay chỉ tiêu khảo sát. Hồ sơ xuất hiện tại Người tham gia (Excel); không tạo câu trả lời khảo sát và không tăng số phản hồi.</p>:<p className="form-hint">Dự án trùng tên sẽ được liên kết; tên dự án cũ chưa có được lưu vào lịch sử. Nhập data không tạo phản hồi khảo sát hay tự duyệt tham gia dự án.</p>}
  <a className="btn btn-secondary btn-sm" href="/api/participants/import" download>Tải file mẫu .xlsx</a>
  <div className="form-group" style={{marginTop:16}}><label className="form-label" htmlFor="data-xlsx">File Excel .xlsx</label><input id="data-xlsx" className="form-input" type="file" accept=".xlsx" disabled={busy} onChange={e=>{setFile(e.target.files[0]||null);setResult(null);setError('');setDone(false);}}/></div>
  {error&&<p role="alert" className="recall-error">{error}</p>}
  {result&&<><p role="status">{done?`Đã thêm ${result.added} hồ sơ`:`${result.valid} hồ sơ có thể nhập`} · {result.skipped} dòng trùng · {result.errors} dòng lỗi</p><div style={{overflow:'auto',maxHeight:350,margin:'16px 0'}}><table className="data-table"><thead><tr><th>Dòng</th><th>Tên</th><th>Năm sinh</th><th>Số điện thoại</th><th>Địa chỉ</th><th>Nghề nghiệp</th><th>Tình trạng hôn nhân</th><th>Dự án tham gia</th><th>Người mời</th><th>Kết quả</th></tr></thead><tbody>{result.rows.map(r=><tr key={r.row}><td>{r.row}</td><td>{r.name||'—'}</td><td>{r.birthYear||'—'}</td><td>{r.phone||'—'}</td><td>{r.address||'—'}</td><td>{r.occupation||'—'}</td><td>{r.maritalStatus||'—'}</td><td>{r.project||'—'}</td><td>{r.inviter||'—'}</td><td>{r.error||r.message||(done?'Đã thêm':r.existing?'Dùng hồ sơ hiện có':'Sẵn sàng')}</td></tr>)}</tbody></table></div>{!done&&result.errors>0&&<p className="form-hint">Chỉ nhập các dòng hợp lệ. Sửa các dòng lỗi trong file rồi nhập lại; hồ sơ đã nhập sẽ được bỏ qua.</p>}</>}
  <div className="recall-actions"><button className="btn btn-secondary" disabled={busy} onClick={onClose}>Đóng</button>{!done&&<button className="btn btn-primary" disabled={busy||!file||Boolean(result&&!result.valid)} onClick={()=>upload(Boolean(result))}>{busy?'Đang xử lý…':result?`Nhập ${result.valid} hồ sơ hợp lệ`:'Kiểm tra và xem trước'}</button>}</div>
 </Modal>;
}
