'use client';
import {useState} from 'react';
const displayDate=date=>date.split('-').reverse().join('/');
export default function RecallScheduleBuilder({value,onChange,preview,error,preserved=[]}){
 const [month,setMonth]=useState(()=>value.dates[0]?.slice(0,7)||new Date(Date.now()+7*3600000).toISOString().slice(0,7));
 const [year,monthNumber]=month.split('-').map(Number);
 const first=new Date(Date.UTC(year,monthNumber-1,1));const offset=(first.getUTCDay()+6)%7;const days=new Date(Date.UTC(year,monthNumber,0)).getUTCDate();
 const update=patch=>onChange({...value,...patch});
 function moveMonth(delta){const date=new Date(Date.UTC(year,monthNumber-1+delta,1));if(date.getUTCFullYear()>=1900&&date.getUTCFullYear()<=9999)setMonth(date.toISOString().slice(0,7));}
 const grouped={};for(const slot of preview){const date=slot.slice(0,10);(grouped[date]??=[]).push(slot.slice(11));}
 return <div className="recall-generator">
  <h3>Ngày đăng ký</h3><p className="form-hint">Bấm để chọn nhiều ngày; bấm lại để bỏ chọn. Có thể chọn ngày ở nhiều tháng.</p>
  <div className="recall-calendar"><div className="recall-calendar-nav"><button type="button" className="btn btn-secondary btn-sm" aria-label="Tháng trước" onClick={()=>moveMonth(-1)}>←</button><input aria-label="Tháng đăng ký" className="form-input" type="month" value={month} min="1900-01" max="9999-12" onChange={e=>{if(/^\d{4}-\d{2}$/.test(e.target.value))setMonth(e.target.value);}}/><button type="button" className="btn btn-secondary btn-sm" aria-label="Tháng sau" onClick={()=>moveMonth(1)}>→</button></div>
   <div className="recall-calendar-grid">{['T2','T3','T4','T5','T6','T7','CN'].map(day=><span className="recall-weekday" key={day}>{day}</span>)}{Array.from({length:offset},(_,i)=><span key={`blank-${i}`}/>)}{Array.from({length:days},(_,i)=>{const date=`${month}-${String(i+1).padStart(2,'0')}`,selected=value.dates.includes(date);return <button type="button" className={`recall-day ${selected?'selected':''}`} key={date} aria-label={`Chọn ngày ${displayDate(date)}`} aria-pressed={selected} onClick={()=>update({dates:selected?value.dates.filter(d=>d!==date):[...value.dates,date].sort()})}>{i+1}</button>;})}</div>
  </div>
  <div className="recall-selected-days">{[...value.dates].sort().map(date=><button type="button" className="btn btn-secondary btn-sm" key={date} aria-label={`Bỏ ngày ${displayDate(date)}`} onClick={()=>update({dates:value.dates.filter(d=>d!==date)})}>{displayDate(date)} ×</button>)}</div>
  <h3>Giờ đăng ký</h3><div className="recall-time-settings"><label className="form-label">Giờ bắt đầu<input className="form-input" type="time" value={value.start} onChange={e=>update({start:e.target.value})}/></label><label className="form-label">Giờ kết thúc<input className="form-input" type="time" value={value.end} onChange={e=>update({end:e.target.value})}/></label><label className="form-label">Khoảng cách (phút)<input className="form-input" type="number" min={1} max={1440} step={1} value={value.interval} onChange={e=>update({interval:e.target.value===''?'':Number(e.target.value)})}/></label></div>
  <h3>Khoảng nghỉ</h3><p className="form-hint">Áp dụng cho tất cả ngày đã chọn. Bỏ các mốc từ giờ bắt đầu nghỉ đến trước giờ kết thúc nghỉ.</p>
  {value.breaks.map((b,i)=><div className="recall-break-row" key={i}><label className="form-label">Bắt đầu nghỉ {i+1}<input className="form-input" type="time" value={b.start} onChange={e=>update({breaks:value.breaks.map((item,j)=>i===j?{...item,start:e.target.value}:item)})}/></label><label className="form-label">Kết thúc nghỉ {i+1}<input className="form-input" type="time" value={b.end} onChange={e=>update({breaks:value.breaks.map((item,j)=>i===j?{...item,end:e.target.value}:item)})}/></label><button type="button" className="btn btn-secondary btn-sm" aria-label={`Xóa khoảng nghỉ ${i+1}`} onClick={()=>update({breaks:value.breaks.filter((_,j)=>i!==j)})}>Xóa</button></div>)}
  <button type="button" className="btn btn-secondary btn-sm" disabled={value.breaks.length>=20} onClick={()=>update({breaks:[...value.breaks,{start:'12:00',end:'13:00'}]})}>+ Thêm khoảng nghỉ</button>
  <div className="recall-schedule-preview"><h3>Xem trước · {preview.length} khung giờ</h3><p className="form-hint">Giữ nhịp tính từ giờ bắt đầu qua các khoảng nghỉ. Giờ kết thúc được nhận nếu trùng một mốc. Đây là giờ đăng ký, không phải thời lượng cuộc hẹn.</p>{error&&<p className="recall-error" role="status">{error}</p>}{preserved.length>0&&<p role="status">Giữ thêm {preserved.length} khung giờ đã có người đăng ký dù nằm ngoài lịch mới.</p>}{Object.entries(grouped).map(([date,times])=><details key={date} open><summary>{displayDate(date)} · {times.length} khung giờ</summary><div className="recall-time-chips">{times.map(time=><span key={time}>{time}{preserved.includes(`${date}T${time}`)?' · đã đăng ký':''}</span>)}</div></details>)}</div>
 </div>;
}
