'use client';
import {use,useEffect,useState} from 'react';
import Link from 'next/link';
function DeliveryRow({person,projectId,onSaved}){
 const [delivered,setDelivered]=useState(person.delivered);
 const [notes,setNotes]=useState(person.notes),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function save(patch){if(Object.hasOwn(patch,'delivered'))setDelivered(patch.delivered);setBusy(true);setError('');try{const res=await fetch(`/api/deliveries/${encodeURIComponent(projectId)}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({participant_id:person.participant_id,...patch})});const data=await res.json();if(!res.ok)throw Error(data.error);setDelivered(data.delivered);onSaved(data);}catch(e){setDelivered(person.delivered);setError(e.message);}finally{setBusy(false);}}
 return <tr><td>{person.name||'Chưa có tên'}</td><td>{person.phone||'Chưa có SĐT'}</td><td style={{minWidth:200,whiteSpace:'normal'}}>{person.address||'Chưa có địa chỉ'}</td><td><label style={{display:'flex',gap:8,alignItems:'center',whiteSpace:'nowrap'}}><input type="checkbox" aria-label={`Đã giao cho ${person.name}`} checked={delivered} disabled={busy} onChange={e=>save({delivered:e.target.checked})}/>{delivered?'Đã giao':'Chưa giao'}</label></td><td style={{minWidth:240}}><textarea aria-label={`Ghi chú cho ${person.name}`} className="form-textarea" rows={2} maxLength={2000} value={notes} disabled={busy} onChange={e=>setNotes(e.target.value)} placeholder="Ghi chú giao mẫu…"/><button className="btn btn-secondary btn-sm" disabled={busy||notes===person.notes} onClick={()=>save({notes})}>{busy?'Đang lưu…':'Lưu ghi chú'}</button>{error&&<p role="alert" style={{color:'var(--danger)'}}>{error}</p>}</td></tr>;
}
export default function ProjectDeliveryPage({params}){
 const {projectId}=use(params);const [data,setData]=useState(null),[error,setError]=useState(''),[revision,setRevision]=useState(0);
 useEffect(()=>{const controller=new AbortController();async function load(){try{const res=await fetch(`/api/deliveries/${encodeURIComponent(projectId)}`,{signal:controller.signal});const result=await res.json();if(!res.ok)throw Error(result.error);if(!controller.signal.aborted){setData({...result,projectId});setError('');}}catch(e){if(!controller.signal.aborted)setError(e.message);}}load();return()=>controller.abort();},[projectId,revision]);
 const ready=data?.projectId===projectId;
 function saved(person){setData(previous=>({...previous,people:previous.people.map(p=>p.participant_id===person.participant_id?person:p)}));}
 return <div><Link href="/admin/deliveries">← Danh sách dự án</Link><div className="page-header" style={{marginTop:20}}><div><h1 className="page-title">Giao mẫu{ready?` · ${data.project.name}`:''}</h1><p>Chỉ hiển thị người có phản hồi được duyệt “Cho tham gia”. Mỗi người một dòng trong dự án.</p></div></div>{error?<div role="alert"><p>{error}</p><button className="btn btn-secondary" onClick={()=>setRevision(v=>v+1)}>Thử lại</button></div>:!ready?<p>Đang tải…</p>:<><p style={{marginBottom:20}}>{data.people.length} người · Đã giao: {data.people.filter(p=>p.delivered).length} · Chưa giao: {data.people.filter(p=>!p.delivered).length}</p>{data.people.length?<div className="card" style={{padding:0,overflowX:'auto'}}><table className="data-table"><thead><tr><th>Tên</th><th>Số điện thoại</th><th>Địa chỉ</th><th>Trạng thái giao</th><th>Ghi chú</th></tr></thead><tbody>{data.people.map(person=><DeliveryRow key={person.participant_id} person={person} projectId={projectId} onSaved={saved}/>)}</tbody></table></div>:<div className="card"><p>Chưa có người được duyệt tham gia dự án.</p><Link href="/admin/responses">Mở Quản lý phản hồi để duyệt</Link></div>}</>}</div>;
}
